# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReasonCounter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReasonCounter
  pod 'Amplitude-iOS', '~> 3.14.1'

end
