// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var AnalyticsJs = require("./analytics.js");

function counterIncrement(oldValue, newValue) {
  AnalyticsJs.counterIncrement(oldValue, newValue);
  return /* () */0;
}

function counterDecrement(oldValue, newValue) {
  AnalyticsJs.counterDecrement(oldValue, newValue);
  return /* () */0;
}

exports.counterIncrement = counterIncrement;
exports.counterDecrement = counterDecrement;
/* ./analytics.js Not a pure module */
