// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';

var AnalyticsJs = require("./analytics.js");

function counterDecrement(oldValue, newValue) {
  AnalyticsJs.counterDecrement(oldValue, newValue);
  return /* () */0;
}

function counterIncrement(oldValue, newValue) {
  AnalyticsJs.counterIncrement(oldValue, newValue);
  return /* () */0;
}

function setup_(options, _) {
  AnalyticsJs.setup_({
        useProductionKey: options.useProductionKey,
        validateProperties: options.validateProperties
      }, { });
  return /* () */0;
}

function setSystemProps_() {
  AnalyticsJs.setSystemProps_({ });
  return /* () */0;
}

exports.counterDecrement = counterDecrement;
exports.counterIncrement = counterIncrement;
exports.setup_ = setup_;
exports.setSystemProps_ = setSystemProps_;
/* ./analytics.js Not a pure module */
