// Generated by AvoCode VERSION 0.0.1, PLEASE EDIT WITH CARE
/* eslint-disable */

var isDev = process.env.NODE_ENV !== 'production';

if (typeof __DEV__ !== 'undefined') {
  isDev = __DEV__;
}

var Amplitude = require('avo-react-native-amplitude-analytics');
var AmplitudeDevApiKey = '321a3172e82317b17d8701f4399c80b9';
var AmplitudeProdApiKey = '9356dbe5889275e08b0e3a685b6f6891';

var asserts;

var setup_ = function(options, systemProps) {
  if (options.validateProperties !== true) {
    isDev = false;
  }

  if (options.useProductionKey === true) {
    console.log('init amplitude with prod key');
    Amplitude.init(AmplitudeProdApiKey);
  } else {
    console.log('init amplitude with dev key');
    Amplitude.init(AmplitudeDevApiKey);
  }
};

var setSystemProps_ = function(systemProps) {};

var counterDecrement = function(oldValue, newValue) {
  if (isDev === true) {
    assertOldValue(oldValue);
    assertNewValue(newValue);
  }

  if (isDev === true) {
    console.log('[avo] Event sent:', 'Counter Decrement', 'Event props:', {
      'Old Value': oldValue,
      'New Value': newValue
    });
  }

  Amplitude.logEvent('Counter Decrement', {
    'Old Value': oldValue,
    'New Value': newValue
  });
};

var counterIncrement = function(oldValue, newValue) {
  if (isDev === true) {
    assertOldValue(oldValue);
    assertNewValue(newValue);
  }

  if (isDev === true) {
    console.log('[avo] Event sent:', 'Counter Increment', 'Event props:', {
      'Old Value': oldValue,
      'New Value': newValue
    });
  }

  Amplitude.logEvent('Counter Increment', {
    'Old Value': oldValue,
    'New Value': newValue
  });
};

if (isDev === true) {
  var assertOldValue = function(oldValue) {
    asserts.assertInt('Old Value', oldValue);
  };

  var assertNewValue = function(newValue) {
    asserts.assertInt('New Value', newValue);
  };
}

exports.setup_ = setup_;
exports.setSystemProps_ = setSystemProps_;
exports.counterDecrement = counterDecrement;
exports.counterIncrement = counterIncrement;

if (isDev === true) {
  asserts = require('avo-assert-js');
}
